import './globals.css'
import type { Metadata } from 'next'
import { sans, serif } from './fonts'
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark text-foreground bg-background text-base'>
      <body className={sans.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
